#!/usr/bin/env bash

source bot_functions
source bot_aliases

for x; do
    case "$x" in
        #-e|--exclamation)
        #    exclamation=1
        #    ;;
        ru|run)
            run=1
            (( commands++ ))
            ;;
        b|bu|bui|buil|build)
            build=1
            (( commands++ ))
            ;;
        re|reb|rebo|reboo|reboot)
            reboot=1
            (( command++ ))
            ;;
        --help)
            bot_usage
            exit 1
            ;;
        *)
            bot_usage
            exit 1
            ;;
    esac
done

#If more than one command is specified
if (( commands != 1 )); then
    if (( commands == 0 )); then
        echo No commands specified!
    else
        echo Only one command can be specified!
    fi

    bot_usage
    exit 1 #Exits
fi

#The different cases
if (( run )); then
    #run
    echo TODO
fi

if (( build )); then
    #build
    echo TODO
fi

if (( reboot )); then
    #reboot
    echo TODO
fi