#!/usr/bin/env bash

usage() {
    cat << EOF
Usage: ${0##*/} [options] command
     bla bla bla.

Commands:
     bla      bla bla bla bla.

Options:
     bla      bla bla bla.
EOF
}

for x; do
    case "$x" in
        -e|--exclamation)
            exclamation=1
            ;;
        sayH|sayHe|sayHel|sayHell|sayHello)
            sayHello=1
            (( commands++ ))
            ;;
        sayB|sayBy|sayBye)
            sayBye=1
            (( commands++ ))
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

if (( commands != 1 )); then
    # somehow warn to use one of either sayHello or SayBye
    usage
    exit 1
fi

if (( sayHello )); then
    text="Hello"
fi
if (( sayBye )); then
    text="Bye"
fi
if (( exclamation )); then
    text="$text""!"
else
    text="$text""."
fi

echo "$text"