#!/usr/bin/env bash

bot_usage() {
    cat << EOF
Usage: ${0##*/} [options] command
    The bot command is used for the Roc-bot
Commands:
    TODO
Options:
    TODO
EOF
}

run_bot(){
    if [ -z $1+x ] && [ -f $1 ]; then
        source $1 #Should contain all that is needed to run
        #Theese are the required vars: TOKEN, DEBUG, VERBOSE, LOG_MESSAGES and IS_EVIL_TWIN

        if [ -z ${TOKEN+x} ]; then echo "Config doesn't contain then TOKEN var!"; exit 1; fi
        if [ -z ${DEBUG+x} ]; then echo "Config doesn't contain then DEBUG var!"; exit 1; fi
        if [ -z ${VERBOSE+x} ]; then echo "Config doesn't contain then VERBOSE var!"; exit 1; fi
        if [ -z ${LOG_MESSAGES+x} ]; then echo "Config doesn't contain then LOG_MESSAGES var!"; exit 1; fi
        if [ -z ${IS_EVIL_TWIN+x} ]; then echo "Config doesn't contain then IS_EVIL_TWIN var!"; exit 1; fi

    else
        echo No config-file specified!; exit 1
    fi
}

